FROM golang:1.17 AS builder
RUN mkdir -p /dut
COPY . /dut
RUN cd /dut && CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o dut ./cmd/main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root
COPY --from=builder ./dut/dut .
ARG PORT
ENV PORT=${PORT}
ARG KOPURO_BASE_URL
ENV KOPURO_BASE_URL=${KOPURO_BASE_URL}
ENTRYPOINT ["/root/dut"]